### PR TITLE
Support Bin/Str format

### PR DESCRIPTION
**Pull request by syohex**
- String is always packed into `Str` format if `utf8` parameter is on, otherwise String is packed into `Bin` format.
- `Str` format is always decoded(like `Encode::decode_utf8($data)`) when unpacked. `Bin` format is decoded if `utf8` parameter is on for compatibility.

### CODE REVIEW

**Comment by gfx** [comment]
LGTM

**Comment by syohex** [comment]
I confirmed that tests of following modules which requires `Data::MessagePack` are passed and can be installed with this version. (Perl 5.22.0, Ubuntu 15.04 x86_64)

- Norikra::Client
- AnyEvent::MessagePack
- Fluent::Logger
- Fluent::AgentLite
- Cache::Redis
- AnyEvent::MPRPC

All related modules are [here](https://metacpan.org/requires/distribution/Data-MessagePack?sort=[[2,1]])

(Some modules cannot be installed by other reasons :-( )

**Comment by syohex** [comment]
I updated for supporting Str format.

**Comment by syohex** [comment]
Please don't merge yet. I don't consider well some points.
- utf8 flag
- How to select Str or Bin for encoding Perl string

**Comment by jamessan** [comment]
Is there any update on this?

**Comment by syohex** [comment]
@jamessan Could you review/test this branch ? I'm not sure whether my implementation works well.

If there are no problems, then I will merge this PR.

**Comment by syohex** [comment]
I confirmed that added tests are passed on 32bit platform.

**Comment by syohex** [comment]
I found some bug. I have fixed them.

**Comment by syohex** [comment]
This msgpack-c revision has issues about big-endian machine. I have to update msgpack-c revision.

**Comment by syohex** [comment]
I update msgpack-c version to 1.4.0 and update unit test.

**Comment by syohex** [comment]
I have confirmed that all tests are passed on big endian machine(Qemu PowerPC 32bit)

```
root@debian-powerpc:~/src/msgpack-perl# uname -a
Linux debian-powerpc 3.2.0-4-powerpc #1 Debian 3.2.51-1 ppc GNU/Linux
root@debian-powerpc:~/src/msgpack-perl# make test
Running Mkbootstrap for Data::MessagePack ()
chmod 644 "MessagePack.bs"
PERL_DL_NONLAZY=1 "/root/local/perl-5.22.1/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'inc', 'blib/lib', 'blib/arch')" t/*.t xt/*.t xt/leaks/*.t
t/00_compile.t .............. 1/1 # Testing Data::MessagePack/0.49 (XS)
# byteoder: 4321, ivsize=4
t/00_compile.t .............. ok
t/01_pack.t ................. ok
t/02_unpack.t ............... ok
t/03_stream_unpack.t ........ ok
t/04_invert.t ............... ok
t/05_preferred_int.t ........ ok
t/06_stream_unpack2.t ....... ok
t/07_break.t ................ ok
t/08_cycle.t ................ ok
t/09_stddata.t .............. ok
t/10_splitted_bytes.t ....... ok
t/11_stream_unpack3.t ....... ok
t/12_stream_unpack4.t ....... ok
t/13_booleans.t ............. ok
t/14_invalid_data.t ......... ok
t/15_utf8.t ................. ok
t/16_unpacker_for_larges.t .. ok
t/17_canonical.t ............ ok
t/18_new_interface.t ........ ok
t/19_utf8_property.t ........ ok
t/20_de.t ................... ok
t/21_dirty_float.t .......... ok
t/22_pid_pack_unpack.t ...... ok
t/23-empty-key.t ............ ok
t/24_tied.t ................. ok
t/40_threads.t .............. ok
t/50_leaktrace.t ............ ok
xt/99_pod.t ................. ok
xt/leaks/normal.t ........... skipped: $ENV{LEAK_TEST} is required
xt/leaks/stream.t ........... skipped: $ENV{LEAK_TEST} is required
All tests successful.

Test Summary Report
-------------------
t/23-empty-key.t          (Wstat: 0 Tests: 3 Failed: 0)
  TODO passed:   1-2
Files=30, Tests=579, 25 wallclock secs ( 3.94 usr  0.85 sys + 17.52 cusr  2.97 csys = 25.28 CPU)
Result: PASS
TESTING: test_pp
"/root/local/perl-5.22.1/bin/perl" -MExtUtils::Command::MM -e "do q[.testenv/test_pp.pl]; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t xt/*.t xt/leaks/*.t
t/00_compile.t .............. 1/1 # Testing Data::MessagePack/0.49 (PP)
# byteoder: 4321, ivsize=4
t/00_compile.t .............. ok
t/01_pack.t ................. ok
t/02_unpack.t ............... ok
t/03_stream_unpack.t ........ ok
t/04_invert.t ............... ok
t/05_preferred_int.t ........ ok
t/06_stream_unpack2.t ....... ok
t/07_break.t ................ ok
t/08_cycle.t ................ ok
t/09_stddata.t .............. ok
t/10_splitted_bytes.t ....... ok
t/11_stream_unpack3.t ....... ok
t/12_stream_unpack4.t ....... ok
t/13_booleans.t ............. ok
t/14_invalid_data.t ......... ok
t/15_utf8.t ................. ok
t/16_unpacker_for_larges.t .. ok
t/17_canonical.t ............ ok
t/18_new_interface.t ........ ok
t/19_utf8_property.t ........ ok
t/20_de.t ................... ok
t/21_dirty_float.t .......... ok
t/22_pid_pack_unpack.t ...... ok
t/23-empty-key.t ............ ok
t/24_tied.t ................. ok
t/40_threads.t .............. ok
t/50_leaktrace.t ............ skipped: disabled in PP
xt/99_pod.t ................. ok
xt/leaks/normal.t ........... skipped: $ENV{LEAK_TEST} is required
xt/leaks/stream.t ........... skipped: $ENV{LEAK_TEST} is required
All tests successful.

Test Summary Report
-------------------
t/23-empty-key.t          (Wstat: 0 Tests: 3 Failed: 0)
  TODO passed:   1-2
Files=30, Tests=573, 36 wallclock secs ( 4.05 usr  0.93 sys + 26.69 cusr  3.87 csys = 35.54 CPU)
Result: PASS
```

**Comment by syohex** [comment]
Tests are passed on CI. https://travis-ci.org/syohex/msgpack-perl

**Comment by syohex** [comment]
@gfx Could you enable travis-ci of this reposity ? I don't have permission of it.

**Comment by syohex** [comment]
@jamessan Please report me if you have any issues about this change.

**Comment by jamessan** [comment]
Thanks! Looks good to me.

**Comment by jamessan** [comment]
Any ETA for an official release with these changes?

**Comment by syohex** [comment]
I already released development version. You can install by following command.

```
% cpanm --dev Data::MessagePack
```

**Comment by jamessan** [comment]
Yes, but that's just a development release. It's unlikely to get packaged by distributions, which is where I would need it.

That's why I asked about an official release, although I guess that was poor wording.

**Comment by syohex** [comment]
Ah, I'll release official version soon. I didn't get any report of development release. I think there is no problem.

**Comment by syohex** [comment]
I have released version 0.50. Please check it.

https://metacpan.org/release/SYOHEX/Data-MessagePack-0.50

**Comment by jamessan** [comment]
Great! Thanks.

**Pull request merged**
